### ISSUE TITLE
Not compatible with FO Browser

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus#65]
Nautilus home displays the loader indefinitely

Browser: Chrome 43 on Android 5.1.1

**Comment by rgaudin** [comment]
![Screenshot_2023-10-24-14-42-40](https://github.com/openzim/nautilus/assets/57929/a52f43ef-a6ef-4b93-981a-301138d513e6)

```
jQuery.Deferred exception: Nautilus is not defined ReferenceError: Nautilus is not defined
    at HTMLDocument.<anonymous> (https://library.kiwix.org/content/maitre_lucas_apprendre_a_dessiner_fr_2023-05/init.js:3:27)
    at e (https://library.kiwix.org/content/maitre_lucas_apprendre_a_dessiner_fr_2023-05/vendors/jquery.min.js:2:29453)
    at t (https://library.kiwix.org/content/maitre_lucas_apprendre_a_dessiner_fr_2023-05/vendors/jquery.min.js:2:29755) undefined
jquery.min.js:2 Uncaught ReferenceError: Nautilus is not defined
```

**Comment by kelson42** [comment]
It has never worked properly or this is a regression introduce recently? If "yes" which version of Nautilus is impacted?

**Comment by rgaudin** [comment]
Same issue in [disledansmalangue_fr_2020-05.zim](https://download.kiwix.org/zim/other/disledansmalangue_fr_2020-05.zim) that's 3 years old. I believe it never worked given that ZIM is one of the ones we created nautilus for.

**Comment by kelson42** [comment]
Here we have to decide if this problem can be fixed…. Or not.

**Comment by kelson42** [comment]
We have decided to do nothing because browsers used there are simply too old and unmaintained.
